/* 05.04.2018 */
ALTER TABLE `slides` ADD COLUMN `is_process_mode` TINYINT(1) NOT NULL DEFAULT 0;

/* 11.04.2018 */
ALTER TABLE `slides` ADD COLUMN `is_mfa_enabled` TINYINT(1) NOT NULL DEFAULT 0;

/* 13.04.2018 */
ALTER TABLE `customers` ADD COLUMN `customer_id` INT DEFAULT NULL;
ALTER TABLE `customers` ADD COLUMN `phone` INT DEFAULT NULL;