spring:
  data:
    rest:
      basePath: /v1
      
  datasource:
    url: jdbc:mysql://localhost:3306/picascrafxzhbcmd?useSSL=false
    username: adminFh4jYg3
    password: yUGL^7GFBlo&97
    
  http:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 50MB

amazon:
  s3:
    accessKeyId: AKIAJXQE3QZTYFLZRHNQ
    secretKey: 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
    bucket: slidepiper-documents-development
    prefix: production/documents
    domain: https://slidepiper-documents-development.s3.amazonaws.com

  ses:
    ses-customer-message:
      accessKeyId: AKIAIFEJNRCXRGWCDTKQ
      secretKey: 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
      
  sns:
    sns-customer-message:
      accessKeyId: AKIAIEJ23APCCYRBVASA
      secretKey: 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

jwt:
  issuer: slidepiper
  secret: "YYeEkSZYKjdo4C$BMH$HQQOan0t@JgDz"

viewer:
  apiUrl: http://127.0.0.2:8080
  
  share:
    data:
      defaultTitle: "SlidePiper Document"
      defaultDescription: "Check out this interactive document!"
      defaultImageUrl: https://s3-us-west-2.amazonaws.com/slidepiper-static/production/images/logo-slidepiper-wide-1200x630.png
